### ISSUE TITLE
MEA: Home page build

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#4]
- [x] Update the logo
- [x] Provide the link for Call for Proposals page
- [x] Change the CTA to Call for Proposals
- [x] Provide local picture for home page
- [x] Update photo on the page
- [x] Provide links for Eventbrite page
- [x] Provide links for Volunteer sign up
- [x] link Content

**Comment by Saallen** [comment]
I have created subtickes so this ticket is a tracker ticket only

**Comment by debloper** [comment]
Waiting for the PNG logos. 
Need the CFP form, for integrating - 
Need the local picture to integate on the homepage
Need to catch up on how to display Eventbrite link & Volunteer sign up CTA

**Comment by Saallen** [comment]
- [x] Waiting for the PNG logos.  @jsan4christ @elioqoshi 
- [x] Need the CFP form, for integrating - 
- [ ] Need the local picture to integate on the homepage- Issue #4 responsable @jsan4christ 
- [ ] Can these be CTA buttons within the How to get involved page? @debloper 
  - [x] Eventbrite link- issue #15- form attached
  - [x] Volunteer sign up CTA - issue #16 - form attached

**Comment by Saallen** [comment]
CFP Google doc - https://docs.google.com/a/mozillafoundation.org/forms/d/1CtTWbpOqfKzrZk1xuq6H0o4xOGe5d9quoIQMEtpRepE/viewform

**Comment by debloper** [comment]
CFP form added as a link to the top navigation. Also, as the main CTA (which previously was to [signing up for updates](http://eepurl.com/Xqn3T))

N.B: I've pushed it in the space of [Contact Us](http://mozilla-uganda.org/blog/?page_id=32) link - which was a 404 & showing some weird directory listing (still the same, if accessed from the footer).

**Comment by arky** [comment]
@debloper I think this is right URI. 

http://mozilla-uganda.org/?page_id=32

**Comment by debloper** [comment]
Hmm... appears so!
Someone has to port the content (as in create a new page) - else let me know if linking to a different domain for "contact me" is a good idea or not. (If it is, I'll just change the URL - no content change required).

**Comment by Saallen** [comment]
Are you guys free to chat on skype?
Would be great to talk through this

**Comment by Saallen** [comment]
On this page the email address should be info@mozfestea.org.
Is anyone able to update?

**Comment by arky** [comment]
@saallen, I am in Bamako with limited internet connectivity. Will keep tracking the problem whenever I could connect to Internet. 

@debloper Looks like I was wrong. There some problem with URL rewriting settings in wordpress. Can someone give admin access to wordpress or shell access to that server.

http://mozfestea.org/2015/?page_id=16
http://mozfestea.org/2015/?page_id=32 (404)

**Comment by debloper** [comment]
Done.
